<?php

namespace ContainerCP5Wa34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdresseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Tf6Ed0O.App\Entity\Adresse' shared service.
     *
     * @return \App\Entity\Adresse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Tf6Ed0O": it needs an instance of "App\\Entity\\Adresse" but this type has been excluded in "config/services.yaml".');
    }
}
