<?php

namespace ContainerCP5Wa34;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BaController' shared autowired service.
     *
     * @return \App\Controller\BaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaController.php';

        $container->services['App\\Controller\\BaController'] = $instance = new \App\Controller\BaController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\BaController', $container));

        return $instance;
    }
}
