<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Adresse extends \App\Entity\Adresse implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Adrcp' => [parent::class, 'Adrcp', null],
        "\0".parent::class."\0".'Adremail' => [parent::class, 'Adremail', null],
        "\0".parent::class."\0".'Adresse' => [parent::class, 'Adresse', null],
        "\0".parent::class."\0".'Adrnom' => [parent::class, 'Adrnom', null],
        "\0".parent::class."\0".'Adrpays' => [parent::class, 'Adrpays', null],
        "\0".parent::class."\0".'Adrprenom' => [parent::class, 'Adrprenom', null],
        "\0".parent::class."\0".'Adrtel' => [parent::class, 'Adrtel', null],
        "\0".parent::class."\0".'Adrville' => [parent::class, 'Adrville', null],
        "\0".parent::class."\0".'commandes' => [parent::class, 'commandes', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'Adrcp' => [parent::class, 'Adrcp', null],
        'Adremail' => [parent::class, 'Adremail', null],
        'Adresse' => [parent::class, 'Adresse', null],
        'Adrnom' => [parent::class, 'Adrnom', null],
        'Adrpays' => [parent::class, 'Adrpays', null],
        'Adrprenom' => [parent::class, 'Adrprenom', null],
        'Adrtel' => [parent::class, 'Adrtel', null],
        'Adrville' => [parent::class, 'Adrville', null],
        'commandes' => [parent::class, 'commandes', null],
        'id' => [parent::class, 'id', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
